### ISSUE TITLE
Fatal: IOError when starting next development iteration

### ISSUE THREAD

**Issue by brson** [sunng87/cargo-release#10]
When publishing [this](https://crates.io/crates/sha2), I saw this error:

```
brian@ip-10-234-25-118:~/dev/rust-sha2⟫ cargo release
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Packaging sha2 v0.1.0 (file:///home/brian/dev/rust-sha2)
   Verifying sha2 v0.1.0 (file:///home/brian/dev/rust-sha2)
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling rustc-serialize v0.3.19
   Compiling sha2 v0.1.0 (file:///home/brian/dev/rust-sha2/target/package/sha2-0.1.0)
   Uploading sha2 v0.1.0 (file:///home/brian/dev/rust-sha2)
Starting next development iteration 0.1.1-pre
Fatal: IOError
third party subcommand `cargo-release` exited unsuccessfully

To learn more, run the command again with --verbose.
```

**Comment by brson** [comment]
If it matters, my `origin` remote is not writable.

**Comment by sunng87** [comment]
This is the last step when cargo release try to push commits and tags to origin. And if you origin is not writable, it fails. It lefts two unpush commits and one tag in your current repo.

**Comment by sunng87** [comment]
@brson this tool will only work for repositories you have write permission because it writes version bump commits to your repo. Do you need an option to write to remote other than `origin`?

**Comment by brson** [comment]
@sunng87 Yes, I typically have origin set to a write-only upstream with `brson` as my own fork.

**Comment by sunng87** [comment]
No problem. I will add an option to set custom origin for final push.

**Comment by sunng87** [comment]
This is supported in 0.5.0 using option `--push-remote <remote-name>` or just `--skip-push`
