### ISSUE TITLE
Cleanup code base?

### ISSUE THREAD

**Issue by epage** [sunng87/cargo-release#102]
My thought is to
- Run rustfmt and add it to the CI
- Fix clippy issues and add it to the CI
- Switch to the 2018 edition.

Creating this issue to first make sure this is all ok.  Since the work is pretty rote, I won't bother waiting on a review once I get the go ahead.  This will be disruptive to other PRs, so I'll do it when I am not aware of any PRs in the queue.

**Comment by epage** [comment]
@sunng87 if you are ok with this, then timing will be important since it'll be disruptive enough that we won't want any active PRs when making the change over.

**Comment by sunng87** [comment]
Thanks @epage , I'm OK with these improvements. Sorry for late response because I have been really busy with both my work and life. I will try best to catch up and respond your PRs in time.

**Comment by epage** [comment]
No problems.  I've been busy as well since I initially did the dependency-version PR.
