### ISSUE TITLE
Option to enforce replacements

### ISSUE THREAD

**Issue by theduke** [sunng87/cargo-release#113]
It would be nice to have a option to enforce replacements, and fail otherwise.

Like:

```
{ file = "..", search = "...", replace = "..", min_matches = 1 }
```

**Comment by epage** [comment]
Good idea!

My initial reaction is to use a real template language.  We then get errors for undefined variables and escaping.  The challenge there is we keep re-rendering the same file which will lose the escaping.

So instead having requirements is a good alternative.  The main question would be what rules to allow.  
- `required = True`
- `min_matches = N`

etc
