### ISSUE TITLE
Dev version in a new branch

### ISSUE THREAD

**Issue by Lokathor** [sunng87/cargo-release#118]
Hello

I tried `cargo release` just now and it worked 99% without any special config, which was great.

However, I'd like it if the "starting work on new development" thing started the work in a branch _other than_ `master`. Just start a new branch with a name from a time stamp or even a totally random name (I'm not picky). I would like as much as possible for the `master` branch to reflect what has been actually released to crates.io, so I'd like the "start of new development" to get pushed into a branch that can be worked on until it's ready and eventually PR'd into `master` and then released.

**Comment by sunng87** [comment]
Thanks! @Lokathor 

In most cases, git tag is what you want to represent the code that pushed to crates.io, instead of master. `cargo-release` manages tags well and keep every release tagged.

**Comment by epage** [comment]
Honestly, that isn't a branching model I've seen before (minus ancient practices that exist at $DAYJOB where something besides git is used).

Generally, the models I see are
- `master` is everything with release branches created when needing to patch past releases
- `master` is where released stuff goes, `develop` is a long-lived branch where all development goes

All that combined with short-lived branches.

**Comment by Lokathor** [comment]
Woah sorry I forgot about this for a few days.

Basically I've got some projects where the code goes along with a tutorial book. Every time a commit hits `master` then TravisCI will run `mdbook` and push that output to the `gh-pages` branch. Effectively every single commit to master is a "release" of sorts because GitHub Pages just hosts the one copy of the book.

As a result, book edits and code edits build up in a side branch until they're fully aligned and enough to put out a new version, then that branch ir PR'd onto `master`.

This branching model might be a little strange, but it's what was suggested to me by others, and it works well for my needs.

If there was an option flag like `--new-work=foobranch` to put the "starting next development" in a side branch that'd be nice. Otherwise I can just use the existing option to suppress the "new work" commit during a release.

**Comment by epage** [comment]
I feel like supporting this directly would lead to a lot of complication because there are a lot of policy involved in this that would be user-specific.
- Is "other" branch long-lived or do we create it?
- Do we merge our master changes back to "other"?
  - How do we merge?
  - How do we keep this safe?

I feel like a simpler approach for this use case is to do releases from "other" and then merge to master what you want published.  This might even be automatable with Github Actions

**Comment by Lokathor** [comment]
Yeah I don't use cargo-release enough any more to really need this. I'd forgotten it was even open.
