### ISSUE TITLE
[workspace] support for not releasing workspace internal tools

### ISSUE THREAD

**Issue by dignifiedquire** [sunng87/cargo-release#120]
On latest `master`, a workspace release publishes members, even though `publish = false` is set.

**Comment by epage** [comment]
That's not good.  I don't have a minute right now to look into this but I'll try to get to this today.

**Comment by dignifiedquire** [comment]
So it does not actually get published, but the version bumping commits happens and the git tagging, which is quite confusing

**Comment by epage** [comment]
Oh, `publish = false` only impacts the ability to publish to crates.io, it does not impact whether something is released or not (ie whether any of the other steps run).

So you are wanting to permanently exclude a workspace member from being released?  A configuration version of `--exclude`?  I'd be curious to know what the use case is for not releasing one of the workspace members.

**Comment by dignifiedquire** [comment]
Yeah. The use case is that it is a benchmarking tool, which only gets run on CI, where the whole source code is present, and is tailored to the other crates in the workspace.

**Comment by epage** [comment]
Makes sense.  I assume `cargo release`'s process isn't harmful, it just creates unnecessary noise.

What more do you need than if, in `$CRATE/release.toml`, you have
```
disable-push = true
disable-publish = true
disable-tag = true
no-dev-version = true
```

That still leaves the version bump.  Is that good enough?  This seems like a less-often use case that if the existing flags work then it probably doesn't need to be made easier with a single flag.

**Comment by dignifiedquire** [comment]
that should be enough yes 👍

**Comment by epage** [comment]
For all the config fields, see https://github.com/sunng87/cargo-release/blob/master/docs/reference.md#config-fields

**Comment by dignifiedquire** [comment]
Thanks a bunch for all the help! I finally managed to release my crates :tada:
