### ISSUE TITLE
[workspace] skip some members

### ISSUE THREAD

**Issue by dignifiedquire** [sunng87/cargo-release#121]
If sth goes wrong, it would be great to be able to skip some workspace members when trying to continue, e.g. `cargo release --except a,b`

**Comment by epage** [comment]
We mimicked how regular cargo commands do this, so in theory it should work to do

`cargo release --exclude a --exclude b`
(can't remember if other cargo commands support `,` or if we do as well)

**Comment by dignifiedquire** [comment]
That works :) I didn't know that, sweet

**Comment by e-nikolov** [comment]
When using `--exclude` with cargo-release v0.11.2 and v0.12.0-beta.6 I get 
`error: Found argument '--exclude' which wasn't expected, or isn't valid in this context`

**Comment by epage** [comment]
Looks like there has not been a new beta release since workspace support was added.  Since I already have it built locally, I've just been doing `cargo run --manifest-path ../cargo-release/Cargo.toml -- ...`
