### ISSUE TITLE
Add `v` into the default tag format?

### ISSUE THREAD

**Issue by epage** [sunng87/cargo-release#124]
Currently, the tag format is `{{prefix}}{{version}}` but I tend to more so see `{{prefix}}v{{version}}` within the rust community.  This makes sense because it makes it easier to do [a search to find version tags](https://github.com/japaric/trust/blob/master/ci/install.sh#L34).

#123 is about making the format customizable.  This is about changing the default, regardless of it being customizable.

**Comment by epage** [comment]
Looks like [semver has a sub-specification encouraging the use of `v`](https://semver.org/spec/v1.0.0.html#tagging-specification-semvertag)

**Comment by epage** [comment]
Apparently, that was removed in the semver 2.0 spec
See https://stackoverflow.com/questions/2006265/is-there-a-standard-naming-convention-for-git-tags for more background on the change.

**Comment by epage** [comment]
Huh, apparently github also recommends the leading `v`
https://github.com/sunng87/cargo-release/releases/new

**Comment by sunng87** [comment]
Sounds good to me. Also with #123 we have a solution to make it backward compatible if user wants consistency.
