### ISSUE TITLE
[regression] Fatal: Invalid TOML file format: error during execution of `cargo metadata`

### ISSUE THREAD

**Issue by LegNeato** [sunng87/cargo-release#129]
Juniper (https://github.com/graphql-rust/juniper/) uses `cargo-release` to test our release pipeline in CI. The most recent release breaks that CI job.

Everything was fine with `cargo-release v0.11.2` and it breaks with `cargo-release v0.12.1`.

```
Fatal: Invalid TOML file format: error during execution of `cargo metadata`: error: failed to parse manifest at `/home/vsts/work/1/s/juniper_codegen/Cargo.toml`

Caused by:
  Dependency 'juniper' has different source paths depending on the build target. Each dependency must have a single canonical source path irrespective of build target.
```

You can see the [command run and output in our CI](https://dev.azure.com/graphql-rust/GraphQL%20Rust/_build/results?buildId=419&view=logs&jobId=7557e248-8325-5ebc-705a-43eaf6e46edd&taskId=a3fec014-b613-5fc6-a87e-7a749699fea8&lineStart=54&lineEnd=55&colStart=1&colEnd=1).

**Comment by LegNeato** [comment]
This was likely broken by workspace support. `juniper` is in a workspace but we run `cargo-release` manually via a build system for each crate.

**Comment by epage** [comment]
> ` error during execution of `cargo metadata`

This is the weird part.  How can cargo-metadata fail on your project and yet it otherwise works fine?

**Comment by epage** [comment]
I bet this is related to our updating dependent dependencies. Itd be helpful if you could post hhe invalid Cargo.toml so we could see what, if anything, we can do.

Dependent version updating can be controlled in the config file or on the command line. See the reference for how to disable it.

**Comment by theduke** [comment]
This is the problematic diff. 

```rust
diff --git a/juniper_codegen/Cargo.toml b/juniper_codegen/Cargo.toml
index 6ce783fc..10294daf 100644
--- a/juniper_codegen/Cargo.toml
+++ b/juniper_codegen/Cargo.toml
@@ -20,6 +20,7 @@ syn = { version = "0.15.28", features = ["full", "extra-traits", "parsing"] }
 quote = "0.6"
 regex = "1"
 lazy_static = "1.0.0"
+juniper = {version = "^0.14.0"}

 [dev-dependencies]
 juniper = { version = "0.13.0", path = "../juniper" }
```

The problem also happens with `0.11.2` so this is not a regression and might be an issue with the configs, I'll look into it further.

**Comment by epage** [comment]
> This is the problematic diff.

Yeah, that explains it.  We read all dependencies and write them back as `dependencies` rather than checking of they are `dev-` or `build-`

See https://github.com/sunng87/cargo-release/blob/master/src/cargo.rs#L92

> Also: the issue happens on 0.11.02 as well, so it's not a regression.

Weird, it doesn't look like our messing with dependencies was in that version

**Comment by theduke** [comment]
> Weird, it doesn't look like our messing with dependencies was in that version 
My bad, this was a mistake on my part, it indeed only happens with `0.12`.
