### ISSUE TITLE
On post-release version bump, update workspace dependencies?

### ISSUE THREAD

**Issue by epage** [sunng87/cargo-release#132]
The problem is `^` by default does not select pre-release but needs to be explicitly mentioned.

See https://github.com/rust-lang/cargo/issues/7007

For past discussion, see https://github.com/sunng87/cargo-release/issues/77

**Comment by antifuchs** [comment]
(Just got bit by this bug)

If I understand the discussion correctly, is the proposal to do all the release steps for the workspace crates, then at the end bump their versions all at once (in one commit maybe)? I think that could work, and would make for a pretty good-looking version history on repos where all the crates get released in lockstep.

**Comment by dmose** [comment]
I just got bit here too.  The idea suggested by @antifuchs seems like a pretty workable solution.

**Comment by dmose** [comment]
One could also imagine walking the dependency graph doing one commit per crate, starting at the leaves of the graph.  That might be a pain to implement, though.

**Comment by epage** [comment]
A lot of the version bumping logic is implemented for pre-release version bumping, so this isn't too hard to implement, it just needs to be done.  I don't personally use the post-release version bump feature, so this hasn't been a priority for me.

**Comment by epage** [comment]
I believe #295 resolves the remaining work for closing this out.  Feel free to open an issue if you run into another corner case.
