### ISSUE TITLE
workspaces: build dependencies still wrongly upgraded

### ISSUE THREAD

**Issue by antifuchs** [sunng87/cargo-release#134]
I'm running cargo-release v0.12.2, with the fix from #130 in place, however it's still misbehaving:

I have a workspace configuration in which one crate depends on another as (and only as!) a build dependency: https://github.com/antifuchs/chars ([chars/Cargo.toml](https://github.com/antifuchs/chars/blob/master/chars/Cargo.toml#L31) and [chars_data/Cargo.toml](https://github.com/antifuchs/chars/blob/master/chars_data/Cargo.toml))

As you can see, `chars/Cargo.toml` has only a build-dependency on chars_data. When using `cargo release`, the build-dependency gets upgraded to a dev-dependency and a regular dependency:

```
$ cargo release --all minor || git diff | cat
Release version chars_data 0.4.0? [y/N]
y
Update chars_data to version 0.4.0
Fatal: Invalid TOML file format: error during execution of `cargo metadata`: error: failed to parse manifest at `/Users/asf/Hacks/chars/chars/Cargo.toml`

Caused by:
  Dependency 'chars_data' has different source paths depending on the build target. Each dependency must have a single canonical source path irrespective of build target.

diff --git a/chars/Cargo.toml b/chars/Cargo.toml
index 09ad98c..f82ebfa 100644
--- a/chars/Cargo.toml
+++ b/chars/Cargo.toml
@@ -23,12 +23,14 @@ unicode-width = "0.1.5"
 byteorder = "1"
 lazy_static = "1.0.0"
 fst = "0.3.0"
+chars_data = {version = "^0.4.0"}

 [dev-dependencies]
 proptest = "0.6.0"
+chars_data = {version = "^0.4.0"}

 [build-dependencies]
-chars_data = {path = "../chars_data", version = "0.3.3-dev"}
+chars_data = {path = "../chars_data", version = "^0.4.0"}

 [features]
 default = []
diff --git a/chars_data/Cargo.toml b/chars_data/Cargo.toml
index 6ca05ae..055949c 100644
--- a/chars_data/Cargo.toml
+++ b/chars_data/Cargo.toml
@@ -1,6 +1,6 @@
 [package]
 name = "chars_data"
-version = "0.3.3-dev"
+version = "0.4.0"
 authors = ["Andreas Fuchs <asf@boinkor.net>"]
 description = "Build-dependency for chars, the unicode character information CLI."
 readme = '../README.md'
```

**Comment by epage** [comment]
Well, thats baffling considering I added a test specifically for that case.  I'll try to reproduce it and see whats going on.

**Comment by antifuchs** [comment]
Agreed! I tried formulating a test case myself, but couldn't find a way to exercise the workspace functionality, specifically (which I guess is where the bug probably hides, since you fixed the per-crate dependency-bumping logic).

**Comment by epage** [comment]
Found it!

It was, yet again, an oversight on my part.  Not good to rush fixes.
