### ISSUE TITLE
"pro-release-commit-message" is a confusing name

### ISSUE THREAD

**Issue by dead10ck** [sunng87/cargo-release#137]
Currently there are two config parameters: `pre-release-commit-message` and `pro-release-commit-message`. At first glance, the second one looks like a typo, but it is not. I think the intended name might have been `post-release-commit-message`, which would more accurately convey what the config option is.

**Comment by epage** [comment]
I agree that the names look confusingly similar.  I am unaware of the background for why `pro` was chosen.

**Comment by sunng87** [comment]
`post-release-commit-message` should be a better name. Let me fix it in next release.
