### ISSUE TITLE
Consolidate workspace commits?

### ISSUE THREAD

**Issue by epage** [sunng87/cargo-release#138]
Currently
- for each crate in a workspace
  - Bump the version in Cargo.toml and update dependents
  - `git commit`
  - `cargo publish`
  - `git tag`
  - Bump the version in Cargo.toml (TODO and update dependents, see #132)
  - `git commit`
  - `git push && git push --tag`

That creates a lot of commit noise.

What if we instead did:
- for each crate in a workspace
  - Bump the version in Cargo.toml and update dependents
- `git commit`
- for each crate in a workspace
  - `cargo publish`
- for each crate in a workspace
  - `git tag`
  - Bump the version in Cargo.toml (TODO and update dependents, see #132)
- `git commit`
- `git push && git push --tag`

This would reduce a lot of commit noise

Open issues
- Recoverability on error: This is why I made `cargo publish` its own loop but haven't thought through the full workflow
- How users should configure commit messages for multi-crate commits

**Comment by grippy** [comment]
I've been playing with `v0.12.4` by running `cargo release --dry-run` on a workspace (multiple crates, single git repo). 

Looking at the current `--dry-run` output this question makes perfect sense to me. As a newbie to this plugin, I'm finding it a little confusing to follow the current output.

Without knowing how the internals work, I wouldn't think it was necessary to cd into and out of workspace member directories for `git (tag, commit, push origin, push origin {tag})`.

Ideally, if we can, just do everything from the workspace folder? Your proposed changes would streamline these steps and cutdown the noise. 👍 

Open issue:

1. One thing you could do is aggregate a single commit from all the member crate versions.

For example:

- `git commit  -am "(cargo-release) Release workspace packages: {package}-v{version}, {package}-v{version}, and {package}-v{version}"`

- `git commit  -am "(cargo-release) Start workspace development iterations: {package}-v{version}, {package}-v{version} and {package}-v{version}"`

**Comment by epage** [comment]
The "cd"ing just represents the CWD when shelling out for commands.  We do this since `cargo release` can be run in on projects besides the CWD.  We do it on every command to make the intent very clear.  If we switch to logging, we could always print the `cd`ing at a lower log level to cut down noise.

**Comment by epage** [comment]
Current state: we now run a step of the process across all crates before moving on to the next step.

What remains: configuring the commit message and sharing the commit.

> One thing you could do is aggregate a single commit from all the member crate versions.
> git commit -am "(cargo-release) Release workspace packages: {package}-v{version}, {package}-v{version}, and {package}-v{version}"

The challenge with that proposal is that the user can customize the commit message and (1) there doesn't seem to be a good way for the user to set that up (2) we don't know the user's format to be able to automatically apply all package/versions like that.

One thought I had is to add a "workspace commit" configuration setting.  We load the workspace's configuration and if the "workspace commit" is in there, we consolidate the commits and us it.  If it isn't in there, then we do individual commits.  We then need to decide what version substitutions to allow.  Its easy if there is a root crate, we can assume to use that one's name and version.  If there isn't ... nothing?
