### ISSUE TITLE
Change commit message template

### ISSUE THREAD

**Issue by lunaryorn** [sunng87/cargo-release#14]
Thanks for this great plugin!  I'm just missing a little piece:  A way to change the commit messages this tool generates. It's just that I typically use a different style for my messages, and I'd love to keep messages in my repo consistent :blush:

Besides, is there a configuration file for `cargo release` where I could add options such as `--sign` to make them permanent, for all contributors to a project?

**Comment by sunng87** [comment]
No problem, in the next release I will add a custom section in Cargo.toml to allow you to configure options like `--sign`, `--doc-branch`. And I will also add commit message template there.

**Comment by lunaryorn** [comment]
Great thank you very much! 😊

**Comment by sunng87** [comment]
Release 0.6.0

BTW, thanks for flycheck. I have been using it in my rust development for a while. It works great.

**Comment by sunng87** [comment]
See the doc for detail:
https://github.com/sunng87/cargo-release#configuration-in-cargotoml
