### ISSUE TITLE
Unexpected manifest re-ordering

### ISSUE THREAD

**Issue by lucab** [sunng87/cargo-release#144]
Something seems to have changed in one recent version of cargo-release, and as a side-effect it is now re-ordering unrelated sections in the `Cargo.toml` manifest.

You can see an example of this in action here: https://github.com/coreos/afterburn/pull/269/files

It did not use to behave that way in the past, see for example here: https://github.com/coreos/afterburn/pull/257

**Comment by epage** [comment]
I suspect this is a bug in the underlying format-preserving toml parser/writer.  We'll need to make a reproduction case to send over to them (`cargo-script` is a great way of doing that)

**Comment by epage** [comment]
I've created a minimal reproduction and posted it as an issue over at toml_edit

See https://github.com/ordian/toml_edit/issues/69

**Comment by lucab** [comment]
@epage @ordian @sunng87 any of you with publishing powers, may I ask for a new release containing #153?
