### ISSUE TITLE
--dry-run option

### ISSUE THREAD

**Issue by goertzenator** [sunng87/cargo-release#15]
I would love to have a dry run option so I can see what it will do before it does it.  I was very nervous running this program for the first time, but it worked great!

**Comment by sunng87** [comment]
It's already there! Running `cargo release --dry-run` will print all shell commands it will execute.

**Comment by goertzenator** [comment]
Excellent!  I suggest mentioning it in the README then.  That command is a big win for newcomers who are apprehensive about what this command really does.

**Comment by sunng87** [comment]
👍  README updated.
