### ISSUE TITLE
Doesn't work with workspacew with combined CHANGELOGs

### ISSUE THREAD

**Issue by asomers** [sunng87/cargo-release#154]
I have a workspace repository (https://github.com/asomers/mockall) containing 3 crates.  It's a proc macro project, so the three crates should logically always be used together; never apart.  So I use a single CHANGELOG.md file at the top of the repository.  But cargo-release tries to edit a CHANGELOG.md file in each crate's directory, and fails.  Could cargo-release please ignore missing CHANGELOG.md files?

**Comment by epage** [comment]
`cargo-release` inherits configuration from the workspace root, including the pre-release replacements.

Some ways of handling this
- Move the root crate into a subfolder so the pre-release replacements are not in the root to be inherited.
- Move your pre-release replacements into your [Cargo.toml file](https://github.com/sunng87/cargo-release/blob/master/docs/reference.md#sources) which will not be inherited
- In each child crate, set pre-release replacements to an empty array, overriding what you are inheriting.

**Comment by epage** [comment]
I'm assuming the provided solutions fixed this for you.  If not, feel free to re-open this.
