### ISSUE TITLE
Not having an upstream repo set should not fail

### ISSUE THREAD

**Issue by dead10ck** [sunng87/cargo-release#155]
The command that cargo release does is `git push`, which assumes that an upstream repo is set for the current branch. It will fail if this is not the case. Having an upstream branch set should not be required.

I think the logic could go something like this:

1. If the upstream remote for the current branch *is* set, then just run `git push`
1. If the upstream remote for the current branch *is not* set *and* the `push-remote` config *is* set, then run `git push <push-remote> <current branch>`
1. If neither the upstream remote for the current branch nor the `push-remote` config is set set, then run `git push origin <current branch>`

**Comment by dead10ck** [comment]
That's not what I was suggesting. My suggestion is to grab the current branch and push to that branch explicitly. Skipping the push is not much different than failing.

**Comment by sunng87** [comment]
I see. That makes sense. However, we still need an explicit remote to push the tag created during release. Extracting tracked branch and remote is possible via matching the output of `git status -sb`.  But that was a little bit hack.

**Comment by dead10ck** [comment]
Sorry, I'm not sure I understand. How is pushing the tag different than pushing the branch? You just get the remote from the `push-remote`, don't you?

**Comment by epage** [comment]
So in reviewing a change I think is related to this, I had a couple of questions to make sure we're delivering the right features for everyone
- What is the use case for releasing without a remote?
- Why is `disable-push` not sufficient?

One of my concerns is that we turn an error (with an opt-out) into "silent" failure when I suspect that for most people it is a critical situation that they'd want to know about.

**Comment by dead10ck** [comment]
@epage Sorry, I'm a bit confused by your question. I can't think of any (useful) use case for doing a release without a remote, but I don't see how that question relates at all to the problem at hand. Nor do I understand how disabling pushing relates.

The problem I reported is that the push command fails when the current branch's upstream branch is not set, and that this problem can be fixed by changing the command from `git push <push-remote>` to `git push <push-remote> <current branch>`.

**Comment by epage** [comment]
> The problem I reported is that the push command fails when the current branch's upstream branch is not set, and that this problem can be fixed by changing the command from git push <push-remote> to git push <push-remote> <current branch>.

This is what I get for rushing in refreshing myself on things while looking at others (the PR I referenced)
