### ISSUE TITLE
tag-message is not respected in 0.12.4

### ISSUE THREAD

**Issue by jonas-schievink** [sunng87/cargo-release#156]
I've set `tag-message = "{{version}}"` here: https://github.com/jonas-schievink/pkg-version/blob/6c0b9628f8e818d26d3ab8c1dcf46f5710ed913f/Cargo.toml#L17

This used to work fine, creating tags "0.1.0" and "0.1.1". However, after updating to cargo-release 0.12.4, it created the tag "v0.1.2" when it should also have been "0.1.2".

**Comment by epage** [comment]
`tag-message` is the description that gets saved off with the tag. The tag itself is `tag-name` and the default for `tag-name` is `{{prefix}}v{{version}}`.  

iirc `tag-name` was not previously configurable, only `tag-prefix`.  When we made it configurable, we changed the behavior from the hard coded `{{prefix}}{{version}}`.

**Comment by epage** [comment]
See also https://github.com/sunng87/cargo-release/issues/123 and https://github.com/sunng87/cargo-release/issues/124

**Comment by jonas-schievink** [comment]
Ah, I see.
