### ISSUE TITLE
Changing default logging level to INFO?

### ISSUE THREAD

**Issue by sunng87** [sunng87/cargo-release#161]
After introducing `log` for logging, the default level doesn't print any information during `cargo-release`, made it difficult to know what's going on and diagnose when error encountered. 

If we change level to `INFO`, which meanings `-vv` is the default, we probably need an inverted option, for example `-q` to reduce log to `WARN` and `-qq` to `ERROR`. I didn't know if any app using `-q` like this. Maybe there is better solution for this?

**Comment by epage** [comment]
I've seen apps use multiple `-q` for this type of thing, so I think it is a reasonable approach. 

I hadn't realized I had significantly reduced the non-dry-run output but it has now been a while.

**Comment by CreepySkeleton** [comment]
I'm totally pro for this!

**Comment by sunng87** [comment]
Thanks. I will take this feature.
