### ISSUE TITLE
Create only one tag if workspace is a single git repo

### ISSUE THREAD

**Issue by CreepySkeleton** [sunng87/cargo-release#162]
For example [my workspace](https://gitlab.com/CreepySkeleton/proc-macro-error) contains two crates: main lib and proc macro attribute for it, the lib depends on the attr.  When cargo release tries to publish this crates it first publishes the attr crate, creates a tag for it, then it tries to create tag for the lib and, of course, fails with `tag x.y.z already exists`

Example output:
```bash
$ cargo release --skip-publish patch
Release version proc-macro-error-attr 0.3.2? [y/N]
y
Update proc-macro-error-attr to version 0.3.2
[cargo_release 5caec6a] v0.3.2
 1 file changed, 1 insertion(+), 1 deletion(-)
Creating git tag v0.3.2
Pushing to git remote
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 2 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 733 bytes | 244.00 KiB/s, done.
Total 7 (delta 4), reused 0 (delta 0)
remote:
remote: To create a merge request for cargo_release, visit:
remote:   https://gitlab.com/CreepySkeleton/proc-macro-error/merge_requests/new?merge_request%5Bsource_branch%5D=cargo_release
remote:
To https://gitlab.com/CreepySkeleton/proc-macro-error.git
   98a7569..5caec6a  cargo_release -> cargo_release
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 164 bytes | 54.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To https://gitlab.com/CreepySkeleton/proc-macro-error.git
 * [new tag]         v0.3.2 -> v0.3.2
Finished proc-macro-error-attr
Release version proc-macro-error 0.3.2? [y/N]
y
Update proc-macro-error to version 0.3.2
[cargo_release 54f64dc] v0.3.2
 1 file changed, 1 insertion(+), 1 deletion(-)
Creating git tag v0.3.2
fatal: tag 'v0.3.2' already exists
```

**Comment by epage** [comment]
Sounds like you are overriding some tag settings which makes it so the tag is the same for all crates?

Skipping out on the tagging would fail for other workspaces (like mine) where not all crates are released every time and so rely on unique tags (which are the default).

I would think instead if you are wanting to control whether to tag or not, you'd configure the crates you don't want tagged to skip it.

**Comment by CreepySkeleton** [comment]
> Sounds like you are overriding some tag settings which makes it so the tag is the same for all crates?
Yes, exactly, every release gets its own unique tag. All the crates get published simultaneously.

> Skipping out on the tagging would fail for other workspaces (like mine) where not all crates are released every time and so rely on unique tags (which are the default).
I see.

> I would think instead if you are wanting to control whether to tag or not, you'd configure the crates you don't want tagged to skip it.
Actually, that's what I do. I just thought it might be good default behavior.

**Comment by epage** [comment]
> Actually, that's what I do. I just thought it might be good default behavior.

One way to get closer to it being a default is to disable tagging in `WORKSPACE_ROOT/release.toml` and then re-enable it in one `CRATE_ROOT/release.toml`.

At this point, I think I'm going to close this since there are use cases this default would block.  Feel free to let me know if anyone disagrees and we can re-open it and discuss it.
