### ISSUE TITLE
A way to commit only once 

### ISSUE THREAD

**Issue by CreepySkeleton** [sunng87/cargo-release#164]
My whole workspace in a single git repo but it contains multiple crates. When I `cargo release` it makes a new commit for every crate (2 in my case). I'd like it to be just one because I always release this crates simultaneously. 

I think `--skip-commit` command line option and `disable-commit = true` manifest key will do the trick.

**Comment by epage** [comment]
I believe this is a dup of https://github.com/sunng87/cargo-release/issues/138 which I'm starting to lay the groundwork for like in https://github.com/sunng87/cargo-release/pull/163

Feel free to re-open if you disageee.
