### ISSUE TITLE
Should file replacements include tag variables?

### ISSUE THREAD

**Issue by epage** [sunng87/cargo-release#165]
In working on https://github.com/sunng87/cargo-release/pull/163, I realized that `{{tag_name}}` is not exposed to the file replacements.  It seems like this could be useful for some styles of changelog maintenance, like with https://raw.githubusercontent.com/assert-rs/predicates-rs/master/CHANGELOG.md

Should we add it in?

**Comment by sunng87** [comment]
SGTM. I think there is no dependencies for `tag_name` generation at the phase of file replacements. It should be safe to move `tag_name` generation earlier and included into variables.
