### ISSUE TITLE
Option to specify development pre-release identifier (or different hard-coded value)

### ISSUE THREAD

**Issue by duelinmarkers** [sunng87/cargo-release#17]
Thanks for cargo-release. It's working great for me [here](https://gitlab.com/duelinmarkers/steel-cent).

Currently cargo-release uses a hard-coded identifier of `pre` when incrementing to the next pre-release version. As I understand the semver spec, alphanumeric pre-release identifiers sort based on ASCII sort order, so `pre` would sort as later than, for example, `alpha` or `beta`, which seems wrong.

One super-easy fix would be to change the hard-coded identifier to `PRE`, since the upper-case alphabet comes before the lower-case in ASCII, but allowing the identifier to be specified via cmd line option & Cargo.toml `package.metadata.release` probably makes more sense.

If you're open to this, I think I'd be able to get a PR done fairly quickly.

Thanks.

**Comment by duelinmarkers** [comment]
I'd propose that the new cmd line and Cargo.toml `package.metadata.release` option be named `development-pre-release-identifiers`.

**Comment by sunng87** [comment]
Sounds good to me. But `development-pre-release-identifiers` is a little bit verbose, how about `dev-version-ext`?

**Comment by duelinmarkers** [comment]
Sounds good. Hopefully I'll have a PR for you soon.

**Comment by sunng87** [comment]
Thank you @duelinmarkers !

**Comment by sunng87** [comment]
Released in `0.7.0-beta.1` using this feature.
