### ISSUE TITLE
Issue with `conventional-changelog`

### ISSUE THREAD

**Issue by dora-gt** [sunng87/cargo-release#172]
Hi,

I wanted to use `cargo release` with [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) but there was a problem.

If we use `cargo release` in a workspace, it would try to tag with like `[crate-name]-[semver]`. On the other hand, `conventional-changelog` tries to gain commit logs, finding tags named like just `[semver]`. So it is not be processed properly.

There might be some solutions:

1. Provide a way to tag without crate name when releasing a workspace, specifying `main` crate. The only `main` crate would be tagged as a pure sem-ver.
1. Provide a way to pass "" (empty string) to the `tag-prefix` option.
1. Provide a way to pass a crate version variable to "tag-name" option value.

Or should I just push a tag of a pure sem-ver without any prefixes manually?

**Comment by epage** [comment]
By default, the root crate is not given a `tag-prefix`.  If you have do not have a root crate in your workspace, then you can override the `tag-prefix` in your "main" crate to be empty.  You can also override `tag-name` but I'm assuming `tag-prefix` is preferred.

See https://github.com/sunng87/cargo-release/blob/master/docs/reference.md#configuration

**Comment by dora-gt** [comment]
Ohhhhh! I see! thank you so much🙇
