### ISSUE TITLE
What happens in a workspace?

### ISSUE THREAD

**Issue by matthiasbeyer** [sunng87/cargo-release#179]
Hi,

I did not yet test anything in here, but I want to ask what would happen in a workspace environment, where crates depend on eachother... 

Right now I'm using [a script](https://git.imag-pim.org/imag/tree/scripts/release.sh) that contains a list of crates and therefore an order in which to release my crates,... would be really nice if cargo-release would do this automagically (or even if there'd be a configuration for that).

I would love to switch to have an automation for this process for [imag](https://imag-pim.org)!

**Comment by epage** [comment]
`cargo-release` has a dry-run mode that makes it relatively easy to see what will happen.  Changing the verbosity will show even more.

`cargo-release` will
- Select crates similarly to `cargo`s rules (including `--all`, `--include`, `--exclude`).  I think our only deviation is lack of support for default-members or whatever it is called.
- Load config for each crate, merging the `Cargo.toml`, `release.toml`, workspace's `release.toml` together.
- Walk through each crate, from bottom of dep tree to top, releasing them
  - We use the crate's directory as the CWD for hooks / replacements
  - When bumping the version of a crate, we'll automatically fix any invalid dependency version ranges in the dependent crates.  This is configurable, from being disabled, to warning, to always modifying the dependency version range.

One point of common confusion is people will put file replacements in the workspace's `release.toml` which then gets applied to every crate but only wanted it applied to the root crate.  Instead put it in the root crate's `Cargo.toml` to ensure it only applies to that one.

**Comment by epage** [comment]
Something that is in-work is to only commit once for a version bump rather than once per crate.

See https://github.com/sunng87/cargo-release/issues/138

**Comment by epage** [comment]
Oh and something we've been iterating on is letting you know when a crate might be unchanged and not needing a release.  See #177 for the latest state of that feature.

**Comment by epage** [comment]
Since there aren't further questions, I'm assuming I can close this.
