### ISSUE TITLE
Support for releasing a pre-release version

### ISSUE THREAD

**Issue by duelinmarkers** [sunng87/cargo-release#18]
I'd like to be able to use cargo-release to release pre-release versions of crates, for example `1.0.0-alpha`.

Currently `level` can be unspecified, `patch`, `minor`, or `major`. In all cases any pre-release identifiers are removed. To support releasing a pre-release version, what I think would make the most sense would be to add a new value for `level`: `pre`, and an additional cmd-line and Cargo option: `pre-release-identifiers`, which would only be used when `level` is `pre`. This is not to be confused w/ the development-pre-release-identifier(s) that will be used (in step 6) when incrementing the version after the release.

**Comment by sunng87** [comment]
My idea is to support `alpha`/`beta` and `rc` for level. Given `--level alpha`, 

* if current version is `dev`/`pre` or released version (say `1.0.0`), change it to `1.0.0-alpha1`
* if current version in alpha like `1.0.0-alpha1`, bump it to `1.0.0-alpha2`
* if current version is `beta` or `rc`, raise an error and abort release

`beta` and `rc` are similar to this.

**Comment by duelinmarkers** [comment]
That sounds pretty good.

What will you do in step 6, where the version would normally be incremented for further development? I'd suggest skipping the increment but setting the `pre` of the version back to the dev value.

It may be better to use `1.0.0-alpha.1` (with dot-separated `alpha` and numeric identifiers) so that `1.0.0-alpha.9` < `1.0.0-alpha.10`.

**Comment by sunng87** [comment]
Adding dot to extension is a good idea! And to correct my previous comment:

if current version is a dev version `1.0.0-dev`, change it to `1.0.0-alpha.1`;
if current version is a released version `1.0.0`, the new version will be `1.0.1-alpha.1`.
