### ISSUE TITLE
Bump to an exact release version

### ISSUE THREAD

**Issue by epage** [sunng87/cargo-release#188]
Example use cases:
- Align on a version across all crates in a workspace
- Bumping major with a pre-release after introducing breaking changes.  Currently you can only bump major or pre-release, not both.

**Comment by sunng87** [comment]
+1 for this case

**Comment by sunng87** [comment]
@epage Did you start working on this? If not I will take this one. This could be particularly useful to me.

**Comment by epage** [comment]
I have not yet.  Feel free.

**Comment by sunng87** [comment]
Thanks!
