### ISSUE TITLE
Vote: 0.13 release

### ISSUE THREAD

**Issue by sunng87** [sunng87/cargo-release#192]
Changelog draft:
https://github.com/sunng87/cargo-release/blob/master/CHANGELOG.md

**Comment by epage** [comment]
Yes, I am not aware of any planned changes that would be breaking, so its safe to release 0.13 without a 0.14 following soon after.

We should probably call out
- #146
- https://github.com/sunng87/cargo-release/commit/7cc989074ff9a40f7f3ee75f4eb6fafbe5eb78b7 (part of #181 but the title doesn't make the breaking change clear)
- https://github.com/sunng87/cargo-release/commit/47bf645e857555ad14048bd458ac9af06acb4236 (one of the useful user-facing parts of #175)
- #168 is important for auto-updating changelogs

btw as a user, I find the keepachangelog format terrible.  "Added", "Changed", and "Removed" are unclear.  I find "Feature", "Fix", and "Breaking Change" are much clearer in the intent.

**Comment by sunng87** [comment]
Changelog updated. I just discovered keepachangelog has updated with a few new section like `Fixed`, `Deprecated` and `Security`. We can probably keep following it because there might be related tools in future. 


Also I suggest updating the unreleased section of changelog in future feature/fix pull request, to make it maintained well.

**Comment by epage** [comment]
Glad to hear they've added those fields.

And yes, I'm used to using change-log generators, so I'm terrible about updating changelogs.  One thing I want to add to my PR auditor (`committed`) is nagging to update the changelog if feature work is done.

**Comment by sunng87** [comment]
0.13.0 released to crates.io
