### ISSUE TITLE
Add option to skip replacement on release

### ISSUE THREAD

**Issue by sunng87** [sunng87/cargo-release#198]
Sometimes when I'm creating pre-release, I don't want the changelog to be updated. It's nice to add an option to skip replacement. This option can be commandline only.

**Comment by epage** [comment]
Is this a dup of https://github.com/sunng87/cargo-release/issues/185 or do you want a CLI flag for this?

**Comment by sunng87** [comment]
Nice. I didn't realize it's already disabled by default. That will be OK for me.
