### ISSUE TITLE
Missing --token flag

### ISSUE THREAD

**Issue by thoward27** [sunng87/cargo-release#202]
The reference describes a flag `--token` to use when publishing, `cargo release --help` doesn't mention it, and trying to use it results in an error:

```
error: Found argument '--token' which wasn't expected, or isn't valid in this context
```

If `--token` is no longer included, what should be used instead?

My goal is to run `cargo release` from a Github workflow, passing in a token would be very helpful.

**Comment by epage** [comment]
How are you "installing" cargo-release?

`--token` has not been released yet.  See https://github.com/sunng87/cargo-release/blob/master/CHANGELOG.md

**Comment by epage** [comment]
@sunng87 can we get a new release made?  Looking at the changelog, it looks like there is a major bug fix plus some improvements that are outstanding.

**Comment by thoward27** [comment]
To install I ran `cargo install cargo-release`, looking forward to your new release! The token feature will be mighty helpful.

**Comment by sunng87** [comment]
@epage `0.13.1` was uploaded. Thank you. 

@thoward27 The token fix should be available via `cargo install`.
