### ISSUE TITLE
Consolidate pre-release-replacements in a workspace?

### ISSUE THREAD

**Issue by antifuchs** [sunng87/cargo-release#205]
I have a crate workspace in github.com/antifuchs/chars, which contains a CHANGELOG.md file in the root; the replacement rules are set in the [release.toml](https://github.com/antifuchs/chars/blob/master/release.toml#L7). Unfortunately, when I run `cargo release -n minor --verbose` (with version 0.13.3), I get the following sequence of events:

```
:;    cargo release -n minor --verbose
[2020-03-20T04:03:05Z DEBUG] Files changed in chars_data since chars_data-v0.4.1: [
        "/Users/asf/Hacks/chars/chars_data/chars_data/Cargo.toml",
        "/Users/asf/Hacks/chars/chars_data/chars_data/data/entities/LICENSE",
        "/Users/asf/Hacks/chars/chars_data/chars_data/data/entities/README.md",
        "/Users/asf/Hacks/chars/chars_data/chars_data/data/entities/entities.json",
        "/Users/asf/Hacks/chars/chars_data/chars_data/data/entities/retrieve.sh",
        "/Users/asf/Hacks/chars/chars_data/chars_data/data/unicode/NameAliases.txt",
        "/Users/asf/Hacks/chars/chars_data/chars_data/data/unicode/UnicodeData.txt",
        "/Users/asf/Hacks/chars/chars_data/chars_data/src/ascii.rs",
        "/Users/asf/Hacks/chars/chars_data/chars_data/src/fst_generator.rs",
        "/Users/asf/Hacks/chars/chars_data/chars_data/src/unicode.rs",
    ]
[2020-03-20T04:03:05Z DEBUG] Files changed in chars since v0.4.1: [
        "/Users/asf/Hacks/chars/chars/chars/Cargo.toml",
        "/Users/asf/Hacks/chars/chars/chars/src/display.rs",
        "/Users/asf/Hacks/chars/chars/chars/tests/human_names.rs",
    ]
[2020-03-20T04:03:05Z INFO ] Update chars_data to version 0.5.0
[2020-03-20T04:03:05Z INFO ] Fixing chars's dependency on chars_data to `^0.5.0` (from `^0.4.1-dev`)
[2020-03-20T04:03:05Z DEBUG] Updating lock file
[2020-03-20T04:03:05Z DEBUG] Substituting values for /Users/asf/Hacks/chars/chars_data/CHANGELOG.md
[2020-03-20T04:03:05Z WARN ] Fatal: IO Error: No such file or directory (os error 2)
```

It looks like cargo-release is trying to do replacements in each child crate's `CHANGELOG.md` file, which I guess could be right for some files in workspace setups, but it's definitely wrong for this one.

Would it be possible to add an option to `pre-release-replacements` that lets cargo-release treat that file as a global one, and consolidate commits?

**Comment by epage** [comment]
> Would it be possible to add an option to pre-release-replacements that lets cargo-release treat that file as a global one, and consolidate commits?

I assume you mean consolidate edits and not consolidate commits.  This could be done but I suspect the standard way of solving this is more applicable.

Generally, a changelog is coupled to one crate.  If nothing else, it is the `{{version}}`.  In that case, the prerelease replacements should be put in that one crate's `release.toml` so it only gets updated when that one crate is released.

There might be cases where a workspace is always released at the same time.  While some work can be done to add a special case for this, I'm not seeing the value compared to work and maintenance of supporting the special case when it can be handled through user configuration.  Granted, my thinking through this trade-off is with me not using this workflow, so I'd love to know if there is any additional input into the value of such a flag.

**Comment by antifuchs** [comment]
Hm, I get that. I didn't talk about the main expectation that I think this behavior violates, in the original bug:

When specifying `file = "CHANGELOG.md"`, I thought that cargo-release would use the file _relative to release.toml_, which sits at the top level of the repo - but instead it relativizes the filenames to each crate root instead. That, together with #157, made for a pretty unclear head-scratching situation (thankfully, `--verbose` exists (-:)

I guess since my two crates aren't going to both get a changelog (one is useful for using in the other's build.rs only), I'll just drop the replacements and keep track manually via release notes for now.

**Comment by epage** [comment]
> I guess since my two crates aren't going to both get a changelog (one is useful for using in the other's build.rs only), I'll just drop the replacements and keep track manually via release notes for now.

Is there a reason you'll do it manually rather than just creating a `release.toml` inside of the `chars` crate with the replacements?  It won't need to contain anything else, inheriting those settings from the workspace.

> When specifying file = "CHANGELOG.md", I thought that cargo-release would use the file relative to release.toml, which sits at the top level of the repo - but instead it relativizes the filenames to each crate root instead. 

Yeah, this is not very clear.  This is a combination of
- Originally we only had crate config and not workspace config (consolidate-commits was the first workspace config)
- Our layered config approach doesn't have an easy way of tracking the relative path for replacements
- Depending on people's mental models, both relative behaviors can make sense.

I wonder if the right thing to do is to add the concept of non-inheritable config. One way of implementing that would be: "if the crate's replacements match the workspace's replacements and the crate isn't in the root, error".  We could start this as a warning.
- Why not error during the merge?  Because the top layer of the config is the args, see https://github.com/sunng87/cargo-release/blob/master/docs/reference.md#sources
- Why check the crate's path?  For single-crate projects, it doesn't matter what config file they use and it can break people unnecessarily

**Comment by antifuchs** [comment]
Argh - I entirely forgot about the ability to have `release.tom` files in each crate that themselves override the workspace settings. Moving the substitutions into the one for the `chars` crate actually worked, entirely perfectly.

Thanks for the thorough explanation!
