### ISSUE TITLE
Support disabling prerelease versions

### ISSUE THREAD

**Issue by bluss** [sunng87/cargo-release#21]
Prerelease versions wreak havoc on internal deps,

for example ndarray-rand depends on ndarray = "0.7". A prerelease version like `0.7.1-pre` can't fill the version requirement "0.7", so it fails to compile in tree.

**Comment by sunng87** [comment]
No problem, I will add an option for this.

**Comment by sunng87** [comment]
@bluss released in 0.7.0-beta.3

**Comment by bluss** [comment]
Great. Thanks, I'll use this for my next releases.
