### ISSUE TITLE
Help message is slightly messed up

### ISSUE THREAD

**Issue by ckaran** [sunng87/cargo-release#212]
Running `cargo help release` yields the following (abbreviated):

```text
$ cargo help release
cargo-release-release 0.13.4
Cargo flags for selecting crates in a workspace

USAGE:
    cargo-release release [OPTIONS] [--] [level-or-version]
```

Normally, we use this tool as `cargo release`, even though `cargo-release` should be in the path.  `cargo-release-release` is not in my path, so I suspect that there is a bug there.

**Comment by sunng87** [comment]
This is a minor issue with the cli parser we use. Are you interested in investigation and making a PR for this?

**Comment by ckaran** [comment]
@sunng87 I wish I had the time to, but I can't.  I'm sorry.

**Comment by epage** [comment]
The help string is coming from `clap-cargo`, we could workaround it in `clap-cargo` like we did in `clap-verbosity-flag`, see https://github.com/rust-cli/clap-verbosity-flag/pull/21

**Comment by epage** [comment]
The underlying structopt bug is https://github.com/TeXitoi/structopt/issues/333

**Comment by epage** [comment]
New clap-cargo released.  Give it a try!

**Comment by ckaran** [comment]
@epage Just pull the latest (`14ecbe336ae1ed7205b4a7f5f4f9783b76b132d5`), and this is what I get:

```text
$ cargo run --release -- release --help
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/cargo-release release --help`
cargo-release-release 0.13.5-alpha.0

USAGE:
    cargo-release release [OPTIONS] [--] [level-or-version]
```

Would I see something different if this were installed rather than run from the command line?

**Comment by epage** [comment]
With the latest `clap-cargo` it is left to `cargo-release`
- `cargo-release --help` is handled by `Command` which doesn't have a help string: https://github.com/sunng87/cargo-release/blob/master/src/main.rs#L1029
- `cargo-release release --help` is handled by `ReleaseOpt` which also doesn't have a help string: https://github.com/sunng87/cargo-release/blob/master/src/main.rs#L830
