### ISSUE TITLE
`cargo release` struggles with patch versions > 20

### ISSUE THREAD

**Issue by woodruffw** [sunng87/cargo-release#214]
This *might* be a user issue, but reporting it just in case it isn't (and in case others have experienced it).

I've been having trouble getting `cargo release` to automatically bump the patch version of a project, specifically when that patch version is already greater than or equal to 20.

My only customization of `cargo release` is disabling dev versions, i.e. the following in my `Cargo.toml`:

```toml
[package.metadata.release]
no-dev-version = true
```

Expected behavior (for a package already released on `0.0.20`):

```bash
$ cargo release --dry-run
[2020-06-08T03:05:42Z INFO ] Update PACKAGE to version 0.0.21
[2020-06-08T03:05:42Z INFO ] Running cargo publish on PACKAGE
[2020-06-08T03:05:42Z INFO ] Pushing HEAD to origin
[2020-06-08T03:05:42Z INFO ] Pushing v0.0.21 to origin
```

Actual behavior:

```bash
$ cargo release --dry-run
[2020-06-08T03:15:50Z INFO ] Running cargo publish on PACKAGE
[2020-06-08T03:15:50Z INFO ] Pushing HEAD to origin
[2020-06-08T03:15:50Z INFO ] Pushing v0.0.20 to origin
```

I expect that the latter would fail, since `v0.0.20` is already published and tagged on `origin`.

I was able to manually force the expected behavior via `cargo release -- 0.0.21`.

**Comment by sunng87** [comment]
Is this happen to 20 specifically?

**Comment by woodruffw** [comment]
As far as I can tell, yes. It didn’t happen below 20.

**Comment by epage** [comment]
```
cargo release --dry-run
```
iirc that releases the current version as-is, removing any pre-release versions that may be attached.

If you want to take v0.0.20 and release `v0.0.21`, run
```
cargo release --dry-run patch
```

**Comment by woodruffw** [comment]
> iirc that releases the current version as-is, removing any pre-release versions that may be attached.

Yes, it looks like you're right -- I was able to confirm this on another project. Somehow I mentally blocked out the `patch` argument before 😅 

Sorry for the false report, and thanks for `cargo release`!
