### ISSUE TITLE
Add option to GPG sign tag without signing commits

### ISSUE THREAD

**Issue by legoktm** [sunng87/cargo-release#216]
I would appreciate an option that allows for just signing the git tag and not the git commits. [This thread](https://web.archive.org/web/20190912220238/http://git.661346.n2.nabble.com/GPG-signing-for-git-commit-td2582986.html) somewhat explains my rationale for not needing signed commits.

**Comment by sunng87** [comment]
Sounds good to me. I will add options to control tag signing and commit signing individually.
