### ISSUE TITLE
Make output of prerelease hook available in replacement variable

### ISSUE THREAD

**Issue by svenstaro** [sunng87/cargo-release#219]
I want to run a command and replace a section in my README.md with the output of that command. More specifically, I want to run `cargo run -- --help` and then have an automatically-updated version of my tool's help in the README.md. I think this functionality would be quite useful to have in general.

**Comment by epage** [comment]
I feel like coupling prerelease hook with replacements could be brittle: if other functionality is needed from prerelease hook then changes could accidentally cause extraneous output in the replacements.

Alternatively, in replacements we could have a `replace_script: "cargo run -- --help` as an alternative to `replace`.

However, this is starting to feel like its getting into the territory of `just`, `xtasks`, or `codegenrs` and am unsure where we should draw the line.  @sunng87 any thoughts?

**Comment by svenstaro** [comment]
That'd work for me. I just need my `--help` in there some way. :P

**Comment by sunng87** [comment]
Yes a typical idea is to build a pipeline framework, and allows data exchange between each stage of the pipeline. When running `cargo-release` we go through the pipeline and execute stage one by one. Tasks like version bumping, publish and git tag can be seen as default or required stage. Users are allowed to insert their own task at any stage. 

But I feel, at least for now, it's an over-kill. The pre-release hook already opened window for some customizations. I prefer to keep `cargo-release` simple and opinionated for now.
