### ISSUE TITLE
Document sign-tag

### ISSUE THREAD

**Issue by svenstaro** [sunng87/cargo-release#220]
It seems the option `sign-tag` exists but it doesn't appear to be documented. I'd document it myself but I don't know whether its lack is intentional or whether it's deprecated or not.

On a tangent, `sign` seems to be a CLI flag but not a config field? It's a bit confusing, to be honest.

**Comment by sunng87** [comment]
In config there is `sign-commit`. I'm going to remove `sign` from cli flag in 0.14, because there is `sign-commit` and `sign-tag` added.

**Comment by svenstaro** [comment]
Alright seems good now after 58a9cf1.
