### ISSUE TITLE
Add option to exclude certain crates when releasing a workspace

### ISSUE THREAD

**Issue by sebschmi** [sunng87/cargo-release#221]
I have a workspace with three crates, two of which are libs I wish to release, and one which is a CLI frontend that should not be on crates.io. It would be nice to be able to ignore the CLI crate from the `release.toml` file, as to never publish it accidentially.

**Comment by sunng87** [comment]
There is an option `disable-publish` for this behaviour. You can find it at https://github.com/sunng87/cargo-release/blob/master/docs/reference.md Also in Cargo.toml you can set `publish=false` to prevent it from publishing to crates.io

Let me know if it works for you.

**Comment by sebschmi** [comment]
Hi,

The `disable-publish` option sounds like a global option, but I did not try it. Setting `publish=false` in the Cargo.toml works though.
Thank you very much.
