### ISSUE TITLE
No --dry-run output by default - update README?

### ISSUE THREAD

**Issue by tmladek** [sunng87/cargo-release#232]
I've ran `cargo release --dry-run` as per the README, only to get a very terse output:

```
$ cargo release --dry-run
[2020-10-20T17:48:42Z INFO ] Update mycrate to version 0.2.6
[2020-10-20T17:48:42Z INFO ] Starting mycrate's next development iteration 0.2.7-alpha.0
[2020-10-20T17:48:42Z INFO ] Pushing HEAD to origin
[2020-10-20T17:48:42Z INFO ] Pushing v0.2.6 to origin
```

I recognized that this is formatted just like `env_logger`, which I use in my crate, so the next thing I tried was `RUST_LOG=trace cargo release --dry-run`, only to get the same output.

So, I looked up issues in this repo related to `--dry-run`, and finally found https://github.com/sunng87/cargo-release/issues/161 - where I discovered that I need to use `cargo release --dry-run -vv` which does output the commands as the README suggests.

This is kind of hard to discover though, especially as not even https://github.com/sunng87/cargo-release/blob/master/docs/reference.md notes that `cargo release` supports the `-v` flag. I am not too experienced with Rust so this might be a common pattern, but I would like to suggest - would it be possible to mention this in the README for newbies like me? :)

Thanks!

**Comment by sunng87** [comment]
Thank you! That's an issue when when changed default log output level. I think a better solute is to set log level to debug by default when `--dry-run` is enabled.

**Comment by sunng87** [comment]
fixed in https://github.com/sunng87/cargo-release/commit/99a1364b387bd40a6c1885532c4fc96c71530db8
