### ISSUE TITLE
cargo release --exclude to have a release.toml equivalent?

### ISSUE THREAD

**Issue by clux** [sunng87/cargo-release#253]
Ideally, `cargo release --exclude examples --exclude tests` (via #121) should also be hardcodable in the config via something like:

```toml
exclude-members = ['examples', 'tests']
```

to allow users to omit `--exclude` flags on `cargo release`.

It's obviously not a big problem at all to just always pass the flags, I just felt that if you have example or test crates, you are unlikely to ever want to release them, and it would be nice to have all the release meta-information declared in the `release.toml`.

You can also use `disable-publish` (as suggested in #221), but it will still bump the various crates, and then you have to publish manually.

**Comment by epage** [comment]
Huh, for some reason I thought you could do this by combining enough flags, but it doesnt look like it.

**Comment by epage** [comment]
If you are still interested, could you give #261 a try?

**Comment by clux** [comment]
Yes, thank you! I can have a go later today.

**Comment by clux** [comment]
Have tried it out. It works, but it's a bit less convenient than what I thought.

This requires you add `release.toml` files (with just `disable-release = true` in its body) to all the members you don't intend to release, and because you don't intend to release these, it feels a bit pointless. It also fractures the niceness of having a single file control everything.

Would you be open to having an vector flag to explicitly list the disabled workespace members?

**Comment by epage** [comment]
You can also put it in the `Cargo.toml` at which point its like `publish = false`.

I'm hesitant to put a global exclude in because that deviates from our existing model where we have enable/disable flags distributed in each crate.  If it was something we were looking at doing in other cases, then it at least establishes a pattern.

**Comment by clux** [comment]
I already have `publish = false` in the relevant `Cargo.toml` files, but it does not pick up on that.

**Comment by epage** [comment]
`publish = false` only controls `cargo publish`, we still do version bumps, tagging, etc.  My intention was to say it would be in the `Cargo.toml`, similar to `publish=False` is in `Cargo.toml`.

It'd look like:
```toml
[package.metadata.release]
disable-release = true
```

**Comment by clux** [comment]
Ah, sorry, I misunderstood. That is better. We can put those properties right next to `publish = false` as well, so that's quite nice. Thanks!
