### ISSUE TITLE
package.metadata.release in virtual workspace

### ISSUE THREAD

**Issue by nilgoyette** [sunng87/cargo-release#255]
In my project thatt contains a virtual manifest, I tried adding 

    [package.metadata.release]
    consolidate-commits = true

and I got this error

    [2021-03-16T13:20:51Z WARN ] Fatal: Invalid TOML file format: Error during execution of `cargo metadata`: error: failed to parse manifest at `/mnt/c/Imeka/diffima/Cargo.toml`

        Caused by:
          missing field `name` for key `package`

So I moved the metadata in the "core" part of my project, which all others subcrates link to. It works without errors but then I see in the dry-run a serie of commits

    cd ...
    git commit  -am (cargo-release) version 1.0.0
    Update ... to version 1.0.0
    Updating lock file
    ... repeat for all subprojects ...

The `consolidate-commits = true` line doesn't seem to be applied.

**Comment by epage** [comment]
Oh interesting, I've never thought of before the problem that you can't have a metadata table in a virtual manifest.

Try putting your configuration in `$WORKSPACE/release.toml`.  See the [reference](https://github.com/sunng87/cargo-release/blob/master/docs/reference.md#sources) for more details.

**Comment by nilgoyette** [comment]
It does work when I use a configuration file. Thank you.
