### ISSUE TITLE
Also update `branch` in badges section with the git tag

### ISSUE THREAD

**Issue by Arnavion** [sunng87/cargo-release#26]
The new `[badges]` section has a `branch` to specify which branch / tag's status should be displayed on crates.io. When cargo-release bumps the version and creates the git tag, it could also update the `branch` specifier for every badge in this section to the git tag of the new release; then that the manifest of the published crate will link to the badge for that release.

Refs:

https://github.com/rust-lang/crates.io/pull/504
https://github.com/rust-lang/cargo/pull/3546
http://doc.crates.io/manifest.html#package-metadata
https://www.integer32.com/2017/01/20/categories-and-ci-badges.html

**Comment by sunng87** [comment]
Good idea! This is what the badge should be displayed on crates.io. Keeping it to master doesn't make much sense IMO. Added to my backlog and will definitely implement this for cargo-release. Thank you!

**Comment by sunng87** [comment]
This is supported in 0.8.0 beta releases via configuration in `Cargo.toml` like:

https://github.com/sunng87/cargo-release/blob/master/Cargo.toml#L23

You can search and replace any file during release process, use `{{version}}` as placeholder of new version number.
