### ISSUE TITLE
Support git push --push-option

### ISSUE THREAD

**Issue by imp** [sunng87/cargo-release#266]
`git push` allows for generic parameters to be added to pass arbitrary strings to the servers. It is done via `--push-option/-o` flag. It is used by gitlab for triggering and manipulating CI (and perhaps used by other systems as well). It would be very useful to allow setting these parameters via `release.toml` or flags.
I would imaging syntax like this:
```
push-options = ["text1", "text2", "key=value"]
```

Which will generate the following git command
```
git push --push-option text1 --push-option text2 --push-option key=value ...
```

**Comment by epage** [comment]
Could you look at #268 to see if it will work for your needs?

**Comment by imp** [comment]
That's perfect! Thanks so much! Any chance to release it to crates.io soon?

**Comment by sunng87** [comment]
A new release 0.15.0 is created for this
