### ISSUE TITLE
New push-options parameter is ignored when listed in Cargo.toml [package.metadata.release]

### ISSUE THREAD

**Issue by imp** [sunng87/cargo-release#269]
I keep all the `cargo-release` configuration in `Cargo.toml`. Apparently newly added `push-option` config param is ignored when listed there under `[package.metadata.release]` table. When listed in `release.toml`, however, everything works as expected.

**Comment by epage** [comment]
(sorry for the delay)

We moved this to be a workspace-wide setting and workspace information can't be stored in `package.metadata`.  

However, I think we should modify this to be both, like with `conslidate-commits`, we have a `consolidate-pushes`
