### ISSUE TITLE
no-dev-version is not read from the config file

### ISSUE THREAD

**Issue by bluss** [sunng87/cargo-release#27]
no-dev-version is not read from the config file

Looks like it's missing here https://github.com/sunng87/cargo-release/blob/7af544590d751ca948aadbd95ba9aed1576af947/src/config.rs#L62

**Comment by bluss** [comment]
(I've been using it as a cli argument all along)

**Comment by bluss** [comment]
(Warning unsolicited advice)  If you say `Fixes #27` (or Fix, or Closes or other words) in the commit message, github will close the issue for you.

**Comment by bluss** [comment]
I should also say: Thanks for fixing this issue so quickly!

**Comment by sunng87** [comment]
This should be fixed in 0.7.1. Please run `cargo install --force cargo-release` to update and verify.

**Comment by sunng87** [comment]
Thank you for pointing out. Usually I don't auto close issue with commits. I'll wait for you to verify and close. 😄

**Comment by bluss** [comment]
It works!
