### ISSUE TITLE
Code modernization

### ISSUE THREAD

**Issue by imp** [sunng87/cargo-release#270]
`cargo release` is a fantastic tool - I surprised I have discovered it only recently! Great job!
While looking at the code I noticed that while `Cargo.toml` specifies `2018` edition the code itself uses older syntax here and there. Would you be willing to accept facelift PR? I can put some time into this provided there are no objections or limitations (like for example, MSRV demands older syntax).

BTW, I see that 1.46 is mentioned in `.travis.yml`, but I am not sure it is indeed in active use. I don't see any MSRV in github workflows.

**Comment by sunng87** [comment]
> Would you be willing to accept facelift PR? 

Yes, of course. Pull request are always welcomed.

I don't have a strong opinion on MSRV so feel free to bump it if there is a reason. We just moved from travis-ci to github actions so the setup is not as completed as on travis-ci. Let me create a patch for that.

**Comment by imp** [comment]
Thanks!
