### ISSUE TITLE
Please restore upload-doc

### ISSUE THREAD

**Issue by asomers** [sunng87/cargo-release#282]
PR #176 removed upload-doc support, on the grounds that docs.rs is a better choice.  However, docs.rs doesn't work for every crate.  In particular, it doesn't work for any crate that uses bindgen in a build.rs file.  Would it be possible to restore it?

**Comment by sunng87** [comment]
The built-in `upload-doc` was considered too specific for github project.

You can still use release hooks or a shell script combined with `cargo release` for that.
