### ISSUE TITLE
Cargo release removes prerelease version

### ISSUE THREAD

**Issue by bluss** [sunng87/cargo-release#29]
It looks like it will attempt to use the wrong version here.

I'm using --no-dev-version because I'm managing the version number myself, don't want cargo release to change and make a commit. Does this make sense?

Version in Cargo.toml is:

```toml
version = "0.9.0-alpha.1"
```

command is: `cargo release --dry-run --no-dev-version`

output:

```rust
cd .
git commit  -am (cargo-release) version 0.9.0
cd -
cargo publish
git tag -a 0.9.0 -m (cargo-release)  version 0.9.0 
git push origin --follow-tags
```

version: cargo-release-release 0.7.1

**Comment by sunng87** [comment]
By default, cargo release increase patch version. If you want to release another alpha version, you need to specify `--level alpha`.

**Comment by bluss** [comment]
Thanks, I had missed that. I usually use it so that cargo release never makes any commits or version bumps at all, just using the currently committed version.

**Comment by sunng87** [comment]
Maybe I can add another level option to disable version bumps.

**Comment by bluss** [comment]
If you think it is a reasonable thing to support. I seem to not be using the tool as intended.
