### ISSUE TITLE
pre-release: generate changelog

### ISSUE THREAD

**Issue by lucab** [sunng87/cargo-release#31]
Capturing the original discussion from https://github.com/nix-rust/nix/issues/595.

As one of the last steps in a release process, there is often the need of semi-automatically generating a changelog.

I'd be better personally happy in having some field to specify a custom binary/script, and some calling convention to follow (e.g. to know about previous and new version, etc.). That way I could extend the process with further logic without making cargo-release too opinionated, and even introduce some interactive action in the middle for a final cosmetic pass.

**Comment by sunng87** [comment]
Yes I agree having a pre-release hook script is a good approach at the moment. Will add this to my backlog.

**Comment by sunng87** [comment]
Just added a quick and simple implementation of pre-release hook.

**Comment by Susurrus** [comment]
Could you provide some documentation for it? I'd like to test it out but I'm not clear on how to use it just from looking at your commit.

**Comment by sunng87** [comment]
For now, just add this to your Cargo.toml:

```
[package.metadata.release]
pre-release-hook = "your-command-or-script"
```

It will be executed when you call `cargo release`. There will be two arguments provided to this script: the new version and current version.

**Comment by Susurrus** [comment]
And I assume that script will also be run during a dry run for easy testing?

**Comment by sunng87** [comment]
No. I just print out the command during dry run, like:

```
Update to version 0.8.1 and commit
Calling pre-release hook: my-script 0.8.1 0.8.1-pre
my-script 0.8.1 0.8.1-pre
cd .
git commit -S -am (cargo-release) version 0.8.1
cd -
Running cargo publish
cargo publish
Creating git tag 0.8.1
git tag -a 0.8.1 -m (cargo-release)  version 0.8.1 -s
Starting next development iteration 0.8.2-pre
cd .
git commit -S -am (cargo-release) start next development iteration 0.8.2-pre
cd -
Pushing to git remote
git push origin --follow-tags
Finished
```
