### ISSUE TITLE
IOError when rewriting version in `Cargo.lock` when project is inside a workspace

### ISSUE THREAD

**Issue by HellButcher** [sunng87/cargo-release#34]
Hi,
I have a workspace layout like this:
```
workspace_root/
+- Cargo.toml
|    [workspace]
|    members = [ "project", ...]
+- Cargo.lock
+- project/
|  +- .git/
|  +- Cargo.toml
|  |    [package]
|  |    name = "project"
|  |    version = "0.1.0"
|  |    ...
|  +- src/
+ ...
```

when I run `cargo release --level patch` inside `project/` (for example),
I get something like this:
```
$ cargo release --level patch
Release version 0.1.1 ? [y/N] y
Update to version 0.1.1 and commit
Fatal: IOError
```

I have looked into the source and found out, that `config::rewrite_cargo_version` tries to read the `Cargo.lock` file from the current directory.
As a workaround, I have copyed the `Cargo.lock` file from the workspace to the project, and the cargo-release worked.

**Comment by sunng87** [comment]
Good catch. This tool wasn't well tested in workspace scenario. I will look into this issue soon.

**Comment by avkonst** [comment]
I have got the same in non workspace scenario

**Comment by avkonst** [comment]
It is the behavior on windows

**Comment by sunng87** [comment]
@avkonst could you please show me a tree view of your project layout? And what's the version of cargo-release you were using?

**Comment by avkonst** [comment]
Cargo.toml:
```
[package]
name = "adapter-node"
version = "0.2.8-alpha.0"
authors = ["konstaan"]
publish = false

[dependencies]
clap = "2.27.1"
error-chain = "0.11.0"
futures = "0.1.14"
hyper = "0.11.2"
tokio-core = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
openssl-probe = "0.1.2"

[dev-dependencies.error-chain-for-dumb-ides]
version = "0"

```

Version:
```
cargo-release.exe-release 0.9.0-beta.6
```

Layout:
```
./.git
./.gitignore
./Cargo.lock
./Cargo.lock.work
./Cargo.toml
./Readme.md
./rust-exp.iml
./src
./src/main.rs
```

**Comment by avkonst** [comment]
shall I report a separate issue for this?

**Comment by sunng87** [comment]
No. I've got the issue. Let me check the code and find a Windows box to reproduce.

**Comment by epage** [comment]
We've changed how we update the lock file (leveraging cargo to do so) so this should now be fixed.  Let us know if you are still having problems.
