### ISSUE TITLE
Add build metadata parameter

### ISSUE THREAD

**Issue by gyscos** [sunng87/cargo-release#35]
The semver specs [defines a build metadata parameter suffix](http://semver.org/#spec-item-10) that can be added to a version, separated by a `+`. Ex: `0.1.0+stable.2017-07-21`. This value is completely ignored for version comparison, and is only used to add information regarding the build.

It would be nice to be add a `--metadata` option to `cargo release` to specify this optional value when publishing a release.

**Comment by sunng87** [comment]
Yes. It sounds good to me. I will find time to support this feature. Thank you!
