### ISSUE TITLE
feature: split commit and publish/push phase

### ISSUE THREAD

**Issue by lucab** [sunng87/cargo-release#36]
This is a feature request to split the release action in two phases: a "commit" and a "publish" one. I'm going to detail my usecase below. I'm willing to start drafting the code for this myself, but I need some guidance on the design/UI points.

In other collaborative projects I've been involved, the process for a release is:
 * a release manager checks that all milestoned bugs/epics/etc are done
 * they open a dedicated branch for the release
 * they run a script `s1` to assemble the changelog and finalize it with editorial changes
 * they run a script `s2` which performs two commits:
   * a first one which bumps all version/references/etc to the actual release
   * a second one which goes back to the development cycle (e.g. `-pre`)
 * this branch is submitted as a normal PR to be reviewed for typos and possible scripted mistakes
 * after final approval, it is merged into master
 * another script `s3` performs the final steps:
   * checks out the real release commit (HEAD^), adds a tag, build all artifacts
   * push the tag to master and publish artifacts in all relevant places

While I don't want to automate all this complex and opinionated process via cargo-release, I would like to able to handle twe two main steps in there (creating the commits and pushing) in two separate phases. @sunng87 do you think it is meaningful to have here? How do you think the CLI should look like?

**Comment by sunng87** [comment]
Hi @lucab , currently you can use `cargo release` as your `s3` script and `s1` and `s2` can be done as your custom process. When cargo-release detects the current version has no dev extension, it will use the version as release version. So I think it works as `s3` in your process.

From my perspective, I want to keep this tool simple to understand. It may not cover all use cases and processes.
