### ISSUE TITLE
Tag prefix cannot be set via `[package.metadata.release]`

### ISSUE THREAD

**Issue by hannobraun** [sunng87/cargo-release#37]
The tag prefix can be set by passing `--tag-prefix <prefix>`, but the same doesn't seem to be possible by setting a `[package.metadata.release]` option in `Cargo.toml`. At least that feature doesn't seem to be documented in the README (unless I missed it).

I tried setting the `tag-prefix` and `prefix` options, but both resulted in an error message.

**Comment by sunng87** [comment]
Not all options available in commandline is configurable in Cargo.toml. I'll add an option for that.

**Comment by hannobraun** [comment]
I guess it would be less surprising and more flexible is all options were available both ways.

Please note that this is not a pressing issue for me. I originally wanted to do it that way, but ended up writing a [shell script](https://github.com/hannobraun/inotify-rs/blob/master/release) that calls cargo-release. This even turned out to be more convenient, as I have two crates in my repository and passing options via the script means less duplication.

In fact, I would prefer if the options for setting the commit and tag messages could be passed via the command line.
