### ISSUE TITLE
cargo-release doesn't trigger AppVeyor tag builds

### ISSUE THREAD

**Issue by luser** [sunng87/cargo-release#43]
I've been using `cargo-release` for publishing my various Rust crates and it's very useful, thanks! I recently configured things on the `sccache` repository to generate releases and publish binary artifacts from Travis / AppVeyor when I tag a release. This is working fine with Travis, but AppVeyor doesn't trigger a build on the tag. I looked into it a bit, and this seems to be the answer:
https://help.appveyor.com/discussions/questions/2133-deploy-setting-for-nuget#comment_39280964

Since `cargo-release` pushes both the tag and the new head of `master` at the same time, AppVeyor doesn't see the tag and so it doesn't trigger our deployment code:
https://github.com/mozilla/sccache/blob/d2c7f925adf0b105a9b87200129d57cf39439ada/appveyor.yml#L41

I think maybe the simple fix here would be to do two pushes: first push just the release tag, and then push the new head of master? (I am not confident that this would actually fix it, though!)

**Comment by sunng87** [comment]
@luser I have changed the push behaviour on master. Could you please build a binary and help me to verify if it work with AppVeyor?

**Comment by luser** [comment]
Thanks! I pulled and built master but I don't see that it's doing anything different with a `cargo release --dry-run`. Here's the output from master:
```
Update to version 0.2.5 and commit
cd .
git commit  -am (cargo-release) version 0.2.5
cd -
Running cargo publish
cargo publish
Creating git tag 0.2.5
git tag -a 0.2.5 -m (cargo-release)  version 0.2.5 
Starting next development iteration 0.2.6-alpha.0
cd .
git commit  -am (cargo-release) start next development iteration 0.2.6-alpha.0
cd -
Pushing to git remote
git push origin --follow-tags
Finished
```

Here's the output from cargo-release 0.7.0, which is what I had installed previously:
```
cd .
git commit  -am (cargo-release) version 0.2.5
cd -
cargo publish
git tag -a 0.2.5 -m (cargo-release)  version 0.2.5 
Starting next development iteration 0.2.6-pre
cd .
git commit  -am (cargo-release) start next development iteration 0.2.6-pre
cd -
git push origin --follow-tags
```

**Comment by sunng87** [comment]
hi @luser, I'm so sorry I forgot to push the commit to github 😭 Could you please test again?

**Comment by luser** [comment]
Oh wait, it looks like it did in fact work, the build just didn't show up right away!
https://ci.appveyor.com/project/luser/sccache2/build/1.0.495

**Comment by sunng87** [comment]
Nice, I will publish this version to crates.io

**Comment by sunng87** [comment]
Released in beta8
