### ISSUE TITLE
Abort release when prerelease hook exits with non-zero exit code

### ISSUE THREAD

**Issue by lunaryorn** [sunng87/cargo-release#44]
Hello,

thank you for `cargo release` ❤️   I'm very happy with it, and I like the prerelease hook feature.

There's just a little issue with it: `cargo release` unfortunately discard the exit code of the hook.

I can use the hook to modify files and add them to the git index, but I can't make any checks or call commands that could fail, because the prerelease hook can't abort the release.  Even if it signals an error with a non-zero exit code, cargo release continues.

I think `cargo release` should abort the release and not commit anything if the prerelease hook exits with a non-zero exit code.

**Comment by sunng87** [comment]
Good suggestion, @lunaryorn. The feature is added into beta6.

prrelease hook is now called before bumping version in `Cargo.toml`

**Comment by lunaryorn** [comment]
@sunng87 Thanks a lot :+1:
