### ISSUE TITLE
Allow pre-release-hook to launch a command with arguments

### ISSUE THREAD

**Issue by avkonst** [sunng87/cargo-release#45]
I believe it is currently possible to set only something like the following:
`pre-release-hook = "./hook.sh"`

I would like to do also, something like the following:
`pre-release-hook = ["./hook.sh", "--my-arg-1", "--my-arg-2"]`
or:
`pre-release-hook = ["bash", "-e", "./hook.sh", "--my-arg-1", "--my-arg-2"]`
and like the following (referring to cargo-make sub-command, which is a bit better than shell scripts):
`pre-release-hook = ["cargo", "make", "some-target"]`

**Comment by sunng87** [comment]
hi @avkonst , since you can run any script here, how about putting arguments into a script? For example, `hook.sh` contains:

```
cargo make some-target
```

**Comment by avkonst** [comment]
I can not do it on windows. It is not os portable.

**Comment by sunng87** [comment]
I see. I'll add support for it.

**Comment by avkonst** [comment]
Great. Thanks!

On 31 Jan 2018 3:46 a.m., "Ning Sun" <notifications@github.com> wrote:

I see. I'll add support for it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sunng87/cargo-release/issues/45#issuecomment-361614898>,
or mute the thread

**Comment by sunng87** [comment]
this feature was released in beta8
