### ISSUE TITLE
Changelog update?

### ISSUE THREAD

**Issue by RazrFalcon** [sunng87/cargo-release#46]
What about support of the [Keep a Changelog](http://keepachangelog.com/en/1.0.0/) format?

All you need to do is to replace this:
```
## [Unreleased]
### Added
- Stuff

[Unreleased]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.1.0...HEAD
[0.1.0]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.0.0...v0.1.0
```
with this:
```
## [Unreleased]

## [0.1.0] - 2017-06-20
### Added
- Stuff

[Unreleased]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.2.0...HEAD
[0.2.0]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.1.0...v0.2.0
[0.1.0]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.0.0...v0.1.0
```

```diff
 ## [Unreleased]
+
+## [0.1.0] - 2017-06-20
 ### Added
 - Stuff
 
-[Unreleased]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.1.0...HEAD
+[Unreleased]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.2.0...HEAD
+[0.2.0]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.1.0...v0.2.0
 [0.1.0]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.0.0...v0.1.0
```

**Comment by sunng87** [comment]
Hi @RazrFalcon , we do have a solution for this.

By use `pre-commit-replacements`, you can get these `Unreleased` replaced by current release version. A working example can be found in my [handlebars Cargo.toml](https://github.com/sunng87/handlebars-rust/blob/master/Cargo.toml#L39). And this is a release diff: https://github.com/sunng87/handlebars-rust/commit/dcbb59a73fee27d05a35d7a3ed7cb8395f8d7ff3

Always keep your CHANGELOG up to date during your development, and cargo-release will deal with the version during a release.

**Comment by RazrFalcon** [comment]
It's a bit different and too manual. Is the a way to automate it completely?

**Comment by sunng87** [comment]
I'm not quite sure if a changelog generated from git log is a good one. And I didn't see a standard method for this.

Anyway if you have your own process and commit log standard, you can still use a `pre-release-hook` to run your own script and generate changelogs.

https://github.com/sunng87/cargo-release/blob/master/Cargo.toml#L27

**Comment by RazrFalcon** [comment]
I don't mean to generate the changelog from git log, rather a changelog update without a manual replacement rules.

**Comment by sunng87** [comment]
The configuration is just oneshot work. Still we don't assume the repo has changelog and the format.

**Comment by sunng87** [comment]
Close this for now.
