### ISSUE TITLE
Use separate config file for cargo release

### ISSUE THREAD

**Issue by sphinxc0re** [sunng87/cargo-release#51]
Most tools in the rust ecosystem use a config file separate to `Cargo.toml`. For example the `rls` uses the `rls.toml` for configuration and `rustfmt` uses the `rustfmt.toml`. In my opinion it would be much cleaner to have a `release.toml` (or something) for configuring this tool.

**Comment by sunng87** [comment]
Good suggestion. I'll add to my backlog. And this could be implemented together with #47

**Comment by sphinxc0re** [comment]
Great idea! Thank you for considering it 😁

**Comment by sphinxc0re** [comment]
But you'd have to implement some kind of migration for people who used the tool before

**Comment by sunng87** [comment]
Yes, that was in my mind. People using config from Cargo.toml will get a deprecation warning.
