### ISSUE TITLE
Use subcommands for release levels

### ISSUE THREAD

**Issue by sphinxc0re** [sunng87/cargo-release#52]
Before you hit **NO!** on your reviewer-keyboard, please let me explain 😉 

The Atom editor has a package management tool called `apm`. It was build for package management but it also helps you publishing atom packages. As it is explained in [here](https://flight-manual.atom.io/hacking-atom/sections/publishing/#publish-your-package) the tool has the following command structure:
```
$ apm publish <major | minor | patch>
```

I find this structure really compelling because it kinda *forces* you to use the tool for versioning and it keeps versioning in particular very organized. So I would like to see a simillar structure in this tool:

```
$ cargo publish <major | minor | patch>
```

**Comment by sunng87** [comment]
Sounds good. :+1: Is this required or optional in atom?

For cargo-release, we also support `rc`, `beta` and `alpha`

**Comment by sphinxc0re** [comment]
It is required when using `apm publish`. Yeah, why not add `rc`, `beta` and `alpha` as well

**Comment by sunng87** [comment]
On my TODO now :+1:

**Comment by sphinxc0re** [comment]
Thank you 😄
