### ISSUE TITLE
Move to `termcolor`

### ISSUE THREAD

**Issue by crlf0710** [sunng87/cargo-release#64]
`cargo-release` is still displaying prompts incorrectly on my windows box (displaying some unsupported escape chars). Since `cargo` is using `termcolor`, I think `cargo-release` should do the same.

**Comment by sunng87** [comment]
@crlf0710 I have #65 working on this. Could you please help me to verify if it works on Windows?

**Comment by crlf0710** [comment]
Sure, I've build the code on that branch, and tested it in a repo with `--dry-run`. The console display (green text) looks fine now.

**Comment by sunng87** [comment]
Thanks! Can you post a screenshot please?
