### ISSUE TITLE
Unhelpful error message when git is not found

### ISSUE THREAD

**Issue by asomers** [sunng87/cargo-release#67]
If git is not installed, then any command other than `--help` will fail with this unhelpful error message:
```
> cargo release --dry-run
Fatal: IO Error: No such file or directory (os error 2)
```

It would be far better for cargo-release to print the name of the file that wasn't found.  As is, I had to use ktrace to find out.

**Comment by asomers** [comment]
gracias!

**Comment by epage** [comment]
btw why was git not installed? Are you using an alternative scm?

**Comment by asomers** [comment]
Not for that project.  I was doing all of my building and testing in a jail, and I only had git installed on the host.  After I figured out what was going on, I realized that I had to install git in the jail, too.

**Comment by epage** [comment]
Thanks for the clarification; wanted to make sure we understand people's use cases and requirements.
