### ISSUE TITLE
Options and cmd line arguments

### ISSUE THREAD

**Issue by sharksforarms** [sunng87/cargo-release#69]
It's easier in CI to work with cmd line arguments as oppose to file configs. I'd like to create a CI job to release my projects following the same release process.

Any config that you specify in a file should also be a command line argument

**Comment by sunng87** [comment]
Hi @sharksforarms , most configurations are available from commandline except replacement and commit messages, which were too long for commandline. I suggest you to put them in a `release.toml` and copy to the project directory when running cargo release.
