### ISSUE TITLE
Require `cargo test` to succeed before `cargo publish`.

### ISSUE THREAD

**Issue by untitaker** [sunng87/cargo-release#7]
Also, I think at this point it'd be nice to have a per-repo config file for such things.

**Comment by sunng87** [comment]
Actually you can use `cargo test && cargo release` to do this

**Comment by untitaker** [comment]
I see, the point though is that I want to have that behavior on a per repo basis

**Comment by sunng87** [comment]
Some tools like Maven runs tests before any important operations. But for rust, in practice, a `cargo test` is insufficient. We may have multiple features to test, and multiple channels of rust to test on.

**Comment by untitaker** [comment]
You're probably right.
