### ISSUE TITLE
Optional tags?

### ISSUE THREAD

**Issue by sharksforarms** [sunng87/cargo-release#72]
Is it possible to disable git tags?

**Comment by sharksforarms** [comment]
The reason I ask is because of this ticket here: https://github.com/RustRPM/cargo-rpm/issues/3

I was going to do a cargo release patch after as my dev version, but wanted to disable the tags.

Is it possible to change the "dev-version" commit to be a patch instead of a "pre-release" ?

**Comment by sunng87** [comment]
For the second question, there is an option `no-dev-version` that won't bump version and won't append prerelease extension to version number.

I will add an option to disable tag.

**Comment by sunng87** [comment]
Released in 0.10.5

**Comment by sharksforarms** [comment]
Perfect, thanks
