### ISSUE TITLE
tag-prefix is being used in a single-crate repo

### ISSUE THREAD

**Issue by jonas-schievink** [sunng87/cargo-release#81]
Reproduction: https://github.com/jonas-schievink/xml-rpc-rs/tree/af9fca89c41cc4f4a8f8480274de372f0be15117

```
$ cargo release --dry-run patch
...
Creating git tag xmlrpc-0.13.1
```

I don't think there should be a tag prefix `xmlrpc-`. The readme says:
> For single-crate repository, we will use version number as git tag name.

This used to work, so this might be a regression in cargo-release.

Additionally, the repository sets `tag-message = "{{version}}"`, which should override cargo-release's default in any case, right? At least that's what I gather from the readme.

(tested with cargo-release 0.11.1 and 0.11.0)

**Comment by sunng87** [comment]
Confirmed. Will you send a pull request to fix this? Otherwise I will do it later today. :smiley:
