### ISSUE TITLE
releasing on Windows requires admin account

### ISSUE THREAD

**Issue by Riduidel** [sunng87/cargo-release#84]
I've performed a release yesterday, which got quite nicely, but failed after quite whole the process was done (crates.io was updated, the tag was created)

Unfortunatly, the release ended with the following error message

     cargo release Fatal: IO Error: Accès refusé. (os error 5)

Do cargo release requires admin account ?

**Comment by sunng87** [comment]
I don't have a Windows machine. But cargo-release should not touch files outside current directory. It just update your Cargo files if you were in minimal configuration. Do you have a full log so I can tell in which step the error occurred?

**Comment by Riduidel** [comment]
Unfortunatly no, I would have to create a new release. But as I'm a total Rust newbie, I don't know if I can remove that test release from crates.io afterwards

**Comment by Riduidel** [comment]
Let me try with a full log ...

**Comment by Riduidel** [comment]
Wait, how can I have full log emitted ?

**Comment by sunng87** [comment]
Yes, you can yank a released version from crates.io

Just send me output of cargo-release will be sufficient.

**Comment by Riduidel** [comment]
Here is an attempt to release using a standard Windows account

	C:\Users\nicolas-delsaux\Documents\open-source\rrss2imap>cargo release
	Release version 0.1.1 ? [y/N] 
	y
	Update to version 0.1.1 and commit
	warning: LF will be replaced by CRLF in Cargo.toml.
	The file will have its original line endings in your working directory
	[master abfc2e8] (cargo-release) version 0.1.1
	 1 file changed, 1 insertion(+), 1 deletion(-)
	Running cargo publish
		Updating crates.io index
		Blocking waiting for file lock on the registry index
		Blocking waiting for file lock on the registry index
		Updating crates.io index
	   Packaging rrss2imap v0.1.1 (C:\Users\nicolas-delsaux\Documents\open-source\rrss2imap)
	   Verifying rrss2imap v0.1.1 (C:\Users\nicolas-delsaux\Documents\open-source\rrss2imap)
		Updating crates.io index
	  Downloaded serde_derive v1.0.88
	  Downloaded aho-corasick v0.6.10
	  Downloaded smallvec v0.6.9
	  Downloaded serde v1.0.88
	  Downloaded new_debug_unreachable v1.0.2
	   Compiling semver-parser v0.7.0
	   Compiling autocfg v0.1.2
	   Compiling winapi v0.3.6
	   Compiling rand_core v0.4.0
	   Compiling proc-macro2 v0.4.27
	   Compiling unicode-xid v0.1.0
	   Compiling siphasher v0.2.3
	   Compiling serde v1.0.88
	   Compiling ryu v0.2.7
	   Compiling string_cache_shared v0.3.0
	... <cutted all dependencies compile> ...
	   Compiling hyper-native-tls v0.2.4
	   Compiling requests v0.0.30
	   Compiling kuchiki v0.7.2
	   Compiling rrss2imap v0.1.1 (C:\Users\nicolas-delsaux\Documents\open-source\rrss2imap\target\package\rrss2imap-0.1.1)
	warning: method is never used: `get_email`
	  --> src\config.rs:45:5
	   |
	45 |     pub fn get_email(&self, default: &Config) -> String {
	   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	   |
	   = note: #[warn(dead_code)] on by default

	warning: method is never used: `is_never_read`
	  --> src\feed.rs:22:5
	   |
	22 |     pub fn is_never_read(feed: &Feed)->bool {
	   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

		Finished dev [unoptimized + debuginfo] target(s) in 5m 50s
	   Uploading rrss2imap v0.1.1 (C:\Users\nicolas-delsaux\Documents\open-source\rrss2imap)
	Creating git tag rrss2imap-0.1.1
	Starting next development iteration 0.1.2-alpha.0
	Fatal: IO Error: Accès refusé. (os error 5)

**Comment by Riduidel** [comment]
Well, I was wrong : running the cargo release command as admin user gave exactly the same result.

**Comment by sunng87** [comment]
This is probably related to an issue with Cargo.lock file not closed. Could you please update your cargo-release to 0.11.2 and test again?

**Comment by Riduidel** [comment]
Oh man, you rock ! THe latest version fixes the bug, and I can run the full release without even using admin account
