### ISSUE TITLE
How to integrate git journal into cargo release ?

### ISSUE THREAD

**Issue by Riduidel** [sunng87/cargo-release#86]
I love the idea of having a changelog, and I would like to maintain this changelog during build using [git journal](https://github.com/saschagrunert/git-journal).

More precisely, I would like to have the `CHANGELOG.md` file having the new section text to be the content of git journal, **and** also having git journal set as commit text (which, as far as I understand) in the releases page of GitHub.
Unfortunatly, it seems like I can only use a small set of variables in `pre-release-replacements`. How can I do that ?

**Comment by Riduidel** [comment]
Oh, and how can I inject that `git journal` content as release commit message (and as a consequence release GitHub page) ?

**Comment by sunng87** [comment]
There is a hook point `pre-release-hook` to execute your own shell script before `cargo release` commit the version changes. You can generate CHANGELOG at the point. 

And you can also use the option `pre-release-commit-message` to set commit message as `git journal`'s output.
