### ISSUE TITLE
How to publish executable crates in GitHub ?

### ISSUE THREAD

**Issue by Riduidel** [sunng87/cargo-release#87]
`cargo release` already pushes zip/.tar.gz in releases page of GitHub and this is cool.
But for crate producing an executable binary, it would be better to have release executable pushed to GitHub. How can we do that ?

**Comment by sunng87** [comment]
Actually tar.gz is not pushed by `cargo release`. It is Github who generated source tarball for each tag automatically. 

I like the idea that we can generate a complete Github release from `cargo release`. Do you know if Github has API to do so?

**Comment by Riduidel** [comment]
well, github has a release api : 
https://developer.github.com/v3/repos/releases/


Process should be

1. create a release 
https://developer.github.com/v3/repos/releases/#create-a-release

2. upload one release asset for each destination platform


In fact, it seems that's what cargo hublish 
(https://github.com/chasinglogic/cargo-hublish) do

Le 28/02/2019 à 08:35, Ning Sun a écrit :

**Comment by sunng87** [comment]
Thanks! I will consider this feature. It's something we like to have in `cargo-release`.

**Comment by epage** [comment]
Considerations
- This would need to run for every platform and for every supported target
- This would require aggregating files the user wants
  - e.g. man pages, completion files, license notifications, etc

Even if someone runs cargo-release in their CI (which I think is an interesting idea but unsure how to decide what commits deserve a new release), there is the problem of most of cargo-release should only be run once rather than Platforms * Targets times.

Currently, the standard solution is to copy the `trust` template which is less than ideal.

The solution I've been working towards (but have been caught up in other projects) is [cargo-tarball](https://github.com/crate-ci/cargo-tarball).  The intent is that you can describe what you want in a tgz/zip and how you want it laid out, and it will generate the tgz/zip for you (solving problems like finding where your artifacts are).  You then just need to make the call to upload to github releases.

**Comment by sunng87** [comment]
So seems a better solution is to provide another hook point, runs after `cargo publish`. User can insert their execution of `cargo-tarball` or `cargo-rpm` into `cargo release` workflow. 

If we really want to generate binaries, we will allow user to configure their desired targets and `cargo release` will create build accordingly. At the moment, the rustup toolchain supports such behaviour.

**Comment by epage** [comment]
> If we really want to generate binaries, we will allow user to configure their desired targets and cargo release will create build accordingly. At the moment, the rustup toolchain supports such behaviour.

I don't think Rust supports cross-compiling between Windows, Linux, and Mac so this would be limited to what targets are supported by what platform cargo-release was run on.

This is why I favor trust's approach of uploading binaries during a tagged commit build in the CI and not encouraging a workflow that involves cargo-release.

**Comment by sunng87** [comment]
Exactly. Checked again it might be possible but pretty difficult to cross compile between OS. 

For the hook point, it's smooth to run after `cargo release` like `cargo release && ./create-github-release.sh`. 

So the requirement can be out of `cargo release`'s scope.

**Comment by Riduidel** [comment]
I'm quite sure there is something i don't understand here.

I can find easily documentations stating that Rust/cargo can perform cross-compilation (as an example this guideline https://github.com/japaric/rust-cross#cross-compiling-with-cargo).

What I would love would be that cargo release integrates that prior to pushing the released artifacts to GitHub.

Is there something I ignore in my "noobness" ?

**Comment by epage** [comment]
Rust supports cross-compilation, but it is generally for compiling other CPU architectures for the same OS.  People improve the coverage some by using [`cross`](https://github.com/japaric/rust-cross) (like cross-compiling FreeBSD from Linux) but even `cross` discourages other forms of cross-OS cross-compilation

> I want to build binaries for Linux, Mac and Windows. How do I cross compile from Linux to Mac?
>
> Short answer: You don't.
>
> It's hard to find a cross C toolchain (and cross compiled C libraries) between different OSes (except perhaps from Linux to Windows). A much simpler and less error prone way is to build natively for these targets because they are tier 1 platforms. You may not have direct access to all these OSes but that's not a problem because you can use CI services like Travis CI and AppVeyor. Check my rust-everywhere project for instructions on how to do that.

https://github.com/japaric/rust-cross#i-want-to-build-binaries-for-linux-mac-and-windows-how-do-i-cross-compile-from-linux-to-mac

**Comment by sunng87** [comment]
Close for now.
