### ISSUE TITLE
Port to git2 crate?

### ISSUE THREAD

**Issue by epage** [sunng87/cargo-release#92]
This would help with #67 but otherwise, I'm unsure of the benefit.

The downside the the API is more complex to deal with.  I did a quick scan and wasn't too sure how to convert some commands into git2 calls.

**Comment by sunng87** [comment]
Just checked git2's docs I'm afraid using libgit2 api brings a lot of complexity on `commit`/`push` operations. To improve usability of #67 issue, we'd better add check to see if `git` binary is on path before everything.
